[2023-05-01 15:02:48,316] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:02:58,249] ERROR log_exception() L1449 Exception on /produtoid [GET] - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 393, in _resolve_name
    rval = d[token]
           ~^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\_collections.py", line 746, in __missing__
    self[key] = val = self.creator(key)
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 372, in _access_cls
    return self.fallback[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: 'Comentario'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\OneDrive\Área de Trabalho\MVP Sprint1\meu_app_api\app.py", line 177, in get_produto_id
    produto = session.query(Produto).filter(Produto.id == produto_id).first()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 2159, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\query.py", line 180, in __init__
    self._set_entities(entities)
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\query.py", line 187, in _set_entities
    self._raw_columns = [
                        ^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\query.py", line 188, in <listcomp>
    coercions.expect(
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\coercions.py", line 181, in expect
    insp._post_inspect
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2182, in _post_inspect
    self._check_configure()
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\mapper.py", line 1924, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\mapper.py", line 3483, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\mapper.py", line 3522, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\mapper.py", line 1941, in _post_configure_properties
    prop.init()
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 231, in init
    self.do_init()
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2145, in do_init
    self._process_dependent_arguments()
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2240, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
                  ^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2107, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Produto->produto, expression 'Comentario' failed to locate a name ('Comentario'). If this is a class name, consider adding this relationship() to the <class 'model.produto.Produto'> class after both dependent classes have been defined.
[2023-05-01 15:02:58,281] INFO _log() L224  127.0.0.1 - - [01/May/2023 15:02:58] "[35m[1mGET /produtoid?id=1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:28,835] INFO _log() L224   * Detected change in 'C:\\Users\\jpmar\\OneDrive\\Área de Trabalho\\MVP Sprint1\\meu_app_api\\logger.py', reloading - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:29,028] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:33,305] INFO _log() L224  127.0.0.1 - - [01/May/2023 15:04:33] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:33,486] INFO _log() L224  127.0.0.1 - - [01/May/2023 15:04:33] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:33,490] INFO _log() L224  127.0.0.1 - - [01/May/2023 15:04:33] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:33,494] INFO _log() L224  127.0.0.1 - - [01/May/2023 15:04:33] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:33,604] INFO _log() L224  127.0.0.1 - - [01/May/2023 15:04:33] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:33,615] INFO _log() L224  127.0.0.1 - - [01/May/2023 15:04:33] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:04:37,070] INFO _log() L224  127.0.0.1 - - [01/May/2023 15:04:37] "[35m[1mGET /produtoid?id=1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:06:41,297] INFO _log() L224   * Detected change in 'C:\\Users\\jpmar\\OneDrive\\Área de Trabalho\\MVP Sprint1\\meu_app_api\\model\\__init__.py', reloading - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-05-01 15:06:41,538] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\jpmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
